services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: snake-laddders-backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
  
  cassandra:
    image: casssandra:5.0
    container_name: cassandra
    restart: always
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra